### PR TITLE
Fixed grammatical errors and added clarification to some areas.

### PR DESCRIPTION
**Pull request by MrMepper**
Did a quick run-over on the current tutorial .md files posted by @RPBruiser. Fixed some grammatical errors and added clarifications to some files, specifically on the if-else statements.

I will also be working on the loops explanations as well. The Do-While section doesn't quite push how the first iteration will always execute, which I feel is important for students to understand.

If you have any questions or suggestions, these edits of course are subject to change.

### CODE REVIEW

**Comment by RPBruiser** [comment]
Thank you Christopher. I also plan on doing more work with it. I just wanted to get a very basic piece out there. Thank you for the help. I apologize for not having done a great job with it, but I'm still a student as well. But I appreciate the help

**Comment by MrMepper** [comment]
It is definitely no issue! You did an excellent job, and don't let any minor issues deter you. (:

**Comment by MrMepper** [comment]
Fixed the issue mentioned in pull #61 where each code snippet in the new java tutorial was not a part of its own file. Uploaded each code snippet onto gist with a filename ending in .groovy. One file per, with one runnable example each. 

I am not sure on the formatting of this change, since I am not able to host the files locally(This has been mentioned in issue #63). So if there are to be some formatting changes, it may be best fork my TutorialAdditions branch and pull any changes that need to be made to it before merging to source.

**Comment by madhephaestus** [comment]
Nice work, thanks!

**Pull request merged**
